[versions]

asciidoctor = "4.0.5"
junit = "5.14.1"
bouncycastle = "1.83"

[plugins]

jmh = { id = "me.champeau.jmh", version = "0.7.3" }
revapi = { id = "org.revapi.revapi-gradle-plugin", version = "1.8.0" }
spotbugs = { id = "com.github.spotbugs", version = "6.4.8" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
svg2ico = { id = "com.gitlab.svg2ico", version = "2.6" }
asciidoctorConvert = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor" }
asciidoctorGems = { id = "org.asciidoctor.jvm.gems", version.ref = "asciidoctor" }

kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.20" }


[libraries]

junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
commonsLang = { group = "org.apache.commons", name = "commons-lang3", version = "3.20.0" }
commonsIO = { group = "commons-io", name = "commons-io", version = "2.21.0" }
ickles = { group = "net.sourceforge.ickles", name = "ickles", version = "0.21" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version = "3.0" }

spotbugs = { group = "com.github.spotbugs", name = "spotbugs", version = "4.8.5" }

asciidoctorTabs = { group = "rubygems", name = "asciidoctor-tabs", version = "1.0.0.beta.6" }

kotlinCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.8.1" }
maverickSynergyClient = { group = "com.sshtools", name = "maverick-synergy-client", version = "3.1.1" }
argo = { group = "net.sourceforge.argo", name = "argo", version = "7.5" }
urin = { group = "net.sourceforge.urin", name = "urin", version = "5.2" }
kotest = { group = "io.kotest", name = "kotest-assertions-core", version = "5.9.1" }
bouncycastleProvider = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
bouncycastlePkix = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastle" }